title: hackndo
email: hackndo@gmail.com
description: This blog talks about computer security. Tutorials about buffer overflow, Active Directory, everything is explained with examples
tagline: Think out of the box
baseurl: "/"
root: /
url: "https://en.hackndo.com"
author: Pixis
twitter_username: hackanddo
github_username:  hackndo
logo: "/assets/icones/logo.png"
social:
    name: Pixis
    links:
        - https://github.com/hackndo
        - https://twitter.com/hackanddo
        - https://www.newbiecontest.org/index.php?page=info_membre&nick=pixis
        - https://www.root-me.org/Betezed
lang: en_US

# Build settings
markdown: kramdown

paginate: 8
paginate_path: "page/:num"
github:
  repo:
    "https://github.com/hackndo/hackndo.github.io"
version: 1.1.0
plugins:
  - jekyll-paginate
  - jekyll-archives
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-redirect-from

excerpt_separator: <!--more-->
